# Jekyll 配置
title: 西北勤務管理系統
description: 專業的社區勤務管理系統
baseurl: ""
url: "https://yourusername.github.io"

# 構建設置
markdown: kramdown
highlighter: rouge
theme: minima

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap

# 排除文件
exclude:
  - README.md
  - package.json
  - node_modules
  - .git
  - .gitignore
  - Gemfile
  - Gemfile.lock

# 包含文件
include:
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.json"
  - "*.png"
  - "*.jpg"
  - "*.jpeg"
  - "*.gif"
  - "*.svg"

# 自定義變量
author: 西北保全
version: 1.0.0
language: zh-TW